services:
  vendure:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Shop API
      - "3001:3001" # Admin API
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=vendure
      - DB_USERNAME=vendure
      - DB_PASSWORD=vendure
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vendure
      POSTGRES_USER: vendure
      POSTGRES_PASSWORD: vendure

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_db_data:
  redis_data:
