name: Deploy Backend

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy Backend to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "87.106.232.199"
          port: "22" # Explizit als String
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "Testing SSH connection..."
            pwd
            whoami
            echo "SSH server status:"
            sudo systemctl status sshd --no-pager || true
            echo "Listening ports:"
            sudo ss -tulpn | grep LISTEN

      - name: Copy files to VPS
        if: success()
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "87.106.232.199"
          port: "22" # Explizit als String
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "."
          target: "~/vendure-backend"

      - name: Setup Environment
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "87.106.232.199"
          port: "22" # Explizit als String
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/vendure-backend

            # Create .env file
            cat > .env << EOL
            APP_ENV=production
            PORT=3000
            DB_NAME=vendure
            DB_SCHEMA=public
            DB_HOST=localhost
            DB_PORT=5432
            DB_USERNAME=vendure
            DB_PASSWORD=vendure
            SUPERADMIN_USERNAME=${{ secrets.VENDURE_ADMIN_USER }}
            SUPERADMIN_PASSWORD=${{ secrets.VENDURE_ADMIN_PASSWORD }}
            COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}
            EOL

      - name: Deploy with Docker
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "87.106.232.199"
          port: "22" # Explizit als String
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/vendure-backend
            docker compose down || true
            docker compose pull || true
            docker compose up -d --build

      - name: Check Deployment
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "87.106.232.199"
          port: "22" # Explizit als String
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/vendure-backend
            echo "Waiting for services to start..."
            sleep 30
            docker compose ps
            docker compose logs --tail=100
